name: fires_flutter
description: All Against Fire

dependencies:
  flutter:
    sdk: flutter
  # i18n
  flutter_localizations:
    sdk: flutter
  intl: "^0.15.6"

  # https://pub.dartlang.org/packages/flutter

  # utils
  simple_moment: "^0.0.3"
  just_debounce_it: "^1.0.4"
  flutter_simple_dependency_injection: "^0.0.2"
  sentry: "^2.0.2"
  flutter_markdown: "^0.1.5"
  url_launcher: "^3.0.2"

  # net
  http: "^0.11.3+16"
  jaguar_resty: "^2.5.5"
  connectivity: "^0.3.1"
  share: "^0.5.2"

  # data
  json_annotation: ^0.2.3
  shared_preferences: "^0.4.2"
  bson_objectid: "^0.1.0"
  comunes_flutter:
    git: git@github.com:comunes/comunes-flutter.git
    # path: /home/vjrj/dev/comunes_flutter
    # version: "^0.0.12"

  # redux
  redux: "^3.0.0"
  flutter_redux: "^0.5.2"
  redux_logging: "^0.3.0"

  # maps, geo, etc
  flutter_map: "^0.0.10"
  flutter_google_places_autocomplete: "^0.0.4"
  location: "^1.3.4"
  geocoder: "^0.0.1"

  # layout
  fluttery: "^0.0.7"
  # https://pub.dartlang.org/packages/padder
  padder: "^1.0.1"
  flutter_fab_dialer: "^0.0.5"

  # firebase
  firebase_messaging: "^1.0.2"

  # icons
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: "^0.1.2"
  community_material_icon: "^0.1.2"

  # not using yet
  # package_info: "^0.3.2"

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^0.8.0
  json_serializable: ^0.5.0

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/private-settings.json
    - assets/pages/privacy-en.md
    - assets/pages/privacy-es.md
    - images/logo-200.png
    - images/fire-marker-l.png
    - images/fire-marker-m.png
    - images/fire-marker-s.png
    - images/fire-marker.png
    - images/industry-marker-reg.png
    - images/industry-marker.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
